# Generated by Django 5.1.5 on 2025-04-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('article', 'news')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.user')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='bookmarks_b_content_a62771_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'content_type', 'object_id'), name='unique_bookmark')],
            },
        ),
    ]
