# Generated by Django 5.1.5 on 2025-04-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bookmarked_by',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
