# Generated by Django 5.1.5 on 2025-01-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('rejected', 'Отклонена'), ('published', 'Опубликована')], default='draft', max_length=20),
        ),
    ]
