# Generated by Django 5.1.5 on 2025-02-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Moderation', 'Moderation'), ('Rejected', 'Rejected'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
