# Generated by Django 5.1.5 on 2025-03-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_image_article_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['published']},
        ),
    ]
