# Generated by Django 5.1.5 on 2025-03-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_article_bookmarked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bookmarked_by',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
