# Generated by Django 5.1.5 on 2025-03-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_bookmarks'),
        ('articles', '0018_remove_article_bookmarked_by_bookmark'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique bookmark',
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user_id', 'article_id'), name='unique bookmark'),
        ),
    ]
