# Generated by Django 5.1.5 on 2025-03-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True, unique_for_date='published'),
        ),
    ]
