# Generated by Django 5.1.5 on 2025-03-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_comment_parent_alter_article_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
