# Generated by Django 5.1.5 on 2025-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_comment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
    ]
