# Generated by Django 5.1.5 on 2025-03-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_articlesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
