# Generated by Django 5.1.5 on 2025-03-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_articlesection_highlight_articlesection_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='quote_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
