# Generated by Django 5.1.5 on 2025-04-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
    ]
