# Generated by Django 5.1.5 on 2025-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_enable_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('Moderation', 'Moderation'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Moderation', max_length=20),
        ),
    ]
