# Generated by Django 5.1.5 on 2025-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_username'),
        ('articles', '0011_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(to='articles.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default/default_user_photo.jpg', null=True, upload_to='photo/'),
        ),
    ]
